cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
import:
  - '@kurone-kito/cspell-config'
ignorePaths:
  - node_modules
  - storybook-static
version: '0.2'
words:
  - amebient
  - cresteaju
  - desync
  - desynced
  - esync
  - graphig
  - momoneko
  - pixiv
  - pylint
  - solidjs
  - toctou
  - towa
  - undispositioned
  - unpushed
  - unreplied
  - unscored
  - unstub
  - vgeek
  - vinxi
  - vocaloid
  - vrcui
  - waivable
