cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
import:
  - '@kurone-kito/cspell-config'
ignorePaths:
  - node_modules
  - storybook-static
  - /scripts
  - /schemas
  - /fixtures/schemas
version: '0.2'
words:
  - agentic
  - amebient
  - cresteaju
  - dedup
  - deprioritize
  - desync
  - desynced
  - dziedzic
  - esync
  - graphig
  - lukasz
  - momoneko
  - onnx
  - pixiv
  - pylint
  - qwen
  - solidjs
  - toctou
  - towa
  - undispositioned
  - unioned
  - unpushed
  - unreplied
  - unscored
  - unstub
  - unwaivable
  - unwaived
  - vgeek
  - vinxi
  - vocaloid
  - vrcui
  - waivable
