concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
name: The CI workflow on push as a feature branch
on:
  push:
    branches:
      - '*'
      - '!main'
permissions:
  contents: read
run-name: Pushed the feature branch by @${{ github.actor }}
jobs:
  build:
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    env:
      COREPACK_INTEGRITY_KEYS: 0
    name: The build process
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Stages the pushed branch
        uses: actions/checkout@v4
      - name: Pre-prepare the Node.js version ${{ matrix.node-version }} environment for the Corepack
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: ${{ matrix.node-version }}
      - name: Enable the corepack
        run: corepack enable
      - name: Post-prepare the Node.js version ${{ matrix.node-version }} environment
        uses: actions/setup-node@v4
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          check-latest: true
          node-version: ${{ matrix.node-version }}
      - env:
          HUSKY: 0
        name: Install the dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ID_OTHERS: ${{ secrets.ID_OTHERS }}
          ID_RELEASE: ${{ secrets.ID_RELEASE }}
          ID_STREAMING: ${{ secrets.ID_STREAMING }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        name: Build the project
        run: pnpm run build
      - name: Check the code style
        run: pnpm run lint
      - name: Run the tests
        run: pnpm run test
      - name: Run the end-to-end tests
        run: pnpm run test:e2e
    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: bash
          - os: windows-latest
            shell: powershell
      fail-fast: false
    timeout-minutes: 30
  deploy:
    name: The staging deploy process
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Stages the pushed branch
        uses: actions/checkout@v4
      - name: Pre-prepare the Node.js environment for the Corepack
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version-file: .node-version
      - name: Enable the corepack because of the pnpm
        run: corepack enable
      - name: Post-prepare the Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          check-latest: true
          node-version-file: .node-version
      - env:
          HUSKY: 0
        name: Install the dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ID_OTHERS: ${{ secrets.ID_OTHERS }}
          ID_RELEASE: ${{ secrets.ID_RELEASE }}
          ID_STREAMING: ${{ secrets.ID_STREAMING }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          TZ: Asia/Tokyo
        name: Run the build
        run: pnpm run build
      - env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NODE_ENV: production
        name: Deploy to Netlify
        # cspell:disable-next-line
        uses: nwtgck/actions-netlify@v3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-deploy: false
          publish-dir: ./packages/web/dist
